verbose: true
world_frame: "map"
color_mode: "normals"

method: "fast"
sensor_horizontal_resolution: 640
sensor_vertical_resolution: 480
sensor_vertical_field_of_view_degrees: 180
integrator_threads: 8

tsdf_voxel_size: 0.05
truncation_distance: 0.15
max_weight: 1000
pointcloud_queue_size: 10
max_ray_length_m: 3 # 14 or 16m would be better, but for that we need better odometry. Otherwise the surface get too damaged.
min_ray_length_m: 0.2
max_consecutive_ray_collisions: 1
use_const_weight: true
use_weight_dropoff: false

# publish_pointclouds_on_update: true
# slice_level: 1.0
# publish_slices: true
# update_mesh_every_n_sec: 1.0

pointcloud_deintegration_queue_length: 100

publish_tsdf_map: true
publish_map_every_n_sec: 15
publish_map_with_trajectory: true